# Generated by Django 5.2.8 on 2025-11-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.chapter'),
            preserve_default=False,
        ),
    ]
