# Generated by Django 5.2.8 on 2025-11-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_lesson_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
